main:
  debug_bijection: false
  compute_metrics: true
  # compute_metrics: false
  plot: true

model:
  # path to model save directory
  directory: null

hardware:
  allow_growth: true
  per_process_gpu_memory_fraction: 0.3
      
hydra:
  job_logging:
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG
  run:
    # dir: /home/nrhinehart/data/esp_infer_results/${now:%Y-%m}/${now:%m-%d-%H-%M-%S}_${dataset.class}
    dir: /home/fireofearth//data/esp_infer_results/${now:%Y-%m}/${now:%m-%d-%H-%M-%S}_${dataset.params.name}

images:
  ext: 'jpg'
  # figsize: [4, 4]
  figsize: [8, 8]

split: 'test'

dataset:
  plot_allchannel: false

plotting:
  bev_kwargs:
    onechannel: False
    allchannel: False
    fmt: 'carla'

defaults:
  - dataset: nuscenes_dataset
